#!/usr/bin/env python3
# Copyright (c) Selqor Labs.
# SPDX-License-Identifier: Apache-2.0

"""Generate and persist the dashboard's Fernet secret key.

FORGE_SECRET_KEY is a 32-byte, url-safe base64 Fernet key used by the
dashboard to encrypt secrets (API keys, tokens, passwords) at rest in
the database. Without a stable key, values encrypted on a previous run
cannot be decrypted after a state-dir rebuild or a fresh clone, which
surfaces as:

    [WARNING] Could not decrypt dashboard secret; keeping stored placeholder value

Usage:
    python scripts/init_secret_key.py              # write to ./.env if unset
    python scripts/init_secret_key.py --print      # print only, don't touch .env
    python scripts/init_secret_key.py --force      # overwrite existing value
    python scripts/init_secret_key.py --env-file path/to/.env

Exit codes:
    0  key is now present in the target file (or was already valid)
    1  invalid arguments or unrecoverable I/O error
    2  key already set and --force was not passed
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

try:
    from cryptography.fernet import Fernet
except ImportError:
    sys.stderr.write(
        "cryptography is not installed. Install project dependencies first:\n"
        "    pip install -e .[dev]\n"
    )
    sys.exit(1)


ENV_VAR = "FORGE_SECRET_KEY"


def generate_key() -> str:
    """Generate a fresh Fernet key as a utf-8 string."""
    return Fernet.generate_key().decode("utf-8")


def key_is_valid(raw: str) -> bool:
    """Return True if *raw* is a valid Fernet key."""
    if not raw:
        return False
    try:
        Fernet(raw.encode("utf-8"))
        return True
    except (ValueError, TypeError):
        return False


def find_existing_value(env_path: Path) -> tuple[str | None, int | None]:
    """Return (value, line_index) for FORGE_SECRET_KEY if present, else (None, None).

    Only considers uncommented lines so a documentation-only ``# FORGE_SECRET_KEY=``
    entry in ``.env.example`` is treated as absent.
    """
    if not env_path.is_file():
        return None, None
    lines = env_path.read_text(encoding="utf-8").splitlines()
    for i, line in enumerate(lines):
        stripped = line.lstrip()
        if stripped.startswith("#"):
            continue
        if "=" not in stripped:
            continue
        name, _, value = stripped.partition("=")
        if name.strip() == ENV_VAR:
            return value.strip().strip('"').strip("'"), i
    return None, None


def write_key(env_path: Path, key: str, existing_line: int | None) -> None:
    """Write *key* into *env_path*, replacing line *existing_line* if given."""
    if env_path.is_file():
        lines = env_path.read_text(encoding="utf-8").splitlines()
    else:
        lines = []

    new_line = f"{ENV_VAR}={key}"

    if existing_line is not None:
        lines[existing_line] = new_line
    else:
        # Append with a leading blank line for readability if the file is non-empty.
        if lines and lines[-1].strip() != "":
            lines.append("")
        lines.append("# Dashboard secret encryption key (Fernet). Generated by scripts/init_secret_key.py.")
        lines.append("# Back this value up alongside your database; losing it makes stored secrets unreadable.")
        lines.append(new_line)

    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # Best-effort tighten permissions on POSIX. Ignore failures (e.g. Windows).
    try:
        os.chmod(env_path, 0o600)
    except OSError:
        pass


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate and persist FORGE_SECRET_KEY for the Selqor MCP Forge dashboard.",
    )
    parser.add_argument(
        "--env-file",
        default=".env",
        help="Path to the .env file to update (default: ./.env).",
    )
    parser.add_argument(
        "--print",
        dest="print_only",
        action="store_true",
        help="Print the generated key and exit without touching any file.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help=(
            "Overwrite an existing FORGE_SECRET_KEY value. "
            "WARNING: secrets encrypted with the old key become unreadable."
        ),
    )
    args = parser.parse_args(argv)

    if args.print_only:
        print(generate_key())
        return 0

    env_path = Path(args.env_file).resolve()
    existing_value, existing_line = find_existing_value(env_path)

    if existing_value and key_is_valid(existing_value) and not args.force:
        print(
            f"{ENV_VAR} is already set in {env_path} and looks valid. Nothing to do.",
            file=sys.stderr,
        )
        print("Re-run with --force to replace it (this will invalidate existing ciphertext).", file=sys.stderr)
        return 2

    if existing_value and not key_is_valid(existing_value):
        print(
            f"{ENV_VAR} in {env_path} is present but not a valid Fernet key. Replacing it.",
            file=sys.stderr,
        )
        # Treat invalid-value case like --force so we clean up the broken entry.
        args.force = True

    key = generate_key()

    try:
        write_key(env_path, key, existing_line if args.force else None)
    except OSError as exc:
        print(f"Failed writing {env_path}: {exc}", file=sys.stderr)
        return 1

    print(f"{ENV_VAR} written to {env_path}")
    print(
        "Next steps:\n"
        "  1. Back up this .env file (or at minimum the FORGE_SECRET_KEY line) alongside your database.\n"
        "  2. In production, set FORGE_SECRET_KEY via your secret manager instead of committing .env.\n"
        "  3. Restart the dashboard: selqor-mcp-forge dashboard --state ./dashboard",
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
